from . import extract_perbase_GCcontent_fromFastQC

__all__ = [extract_perbase_GCcontent_fromFastQC]

from .extract_perbase_GCcontent_fromFastQC import extract_perbase_GCContentRowsFromFastQC, perbasegccontent
